#!/bin/bash
SCRIPT_PATH="$(cd $(dirname "$BASH_SOURCE"); dirname "$(pwd)")/../.."

# setup the environment to not mess with the system
export DYLD_FALLBACK_LIBRARY_PATH="${SCRIPT_PATH}/lib:$DYLD_FALLBACK_LIBRARY_PATH"
export LD_PRELOAD_PATH="${SCRIPT_PATH}/lib"
export GST_REGISTRY="${SCRIPT_PATH}/Resources/gst.registry"
export GST_PLUGIN_SCANNER="${SCRIPT_PATH}/Resources/gst-plugin-scanner"
export GTK_PATH="${SCRIPT_PATH}/Frameworks/GStreamer.framework/Versions/Current"
export GST_PLUGIN_SYSTEM_PATH="${SCRIPT_PATH}/Frameworks/GStreamer.framework/Versions/Current/lib/gstreamer-1.0"
export GIO_EXTRA_MODULES="${SCRIPT_PATH}/Frameworks/GStreamer.framework/Versions/Current/lib/gio/modules"
export KIVY_HOME="${SCRIPT_PATH}/Resources/.kivy"
